### ISSUE TITLE
History für Warnungen

### ISSUE THREAD

**Issue by sigi2345** [ticaki/ioBroker.weather-warnings#10]
**Describe the solution you'd like**

Eine History im JSON TABLE Format für eine Tabelle zur Anzeige in VIS-2

**Describe alternatives you've considered**

Tabelle:

Datum - Provider - warntypename - warnlevelnumber

LG
Sigi

**Comment by ticaki** [comment]
Möglich, aber bis das gut funktioniert wird ein bissle dauern. Die Gewitteraktualisierung im Minuten Takt sehe ich da als schwierig an. Mal sehen ob ich es schaffe die sauber raus zu filtern.
