### ISSUE TITLE
JSON Table 

### ISSUE THREAD

**Issue by sigi2345** [ticaki/ioBroker.weather-warnings#11]
**Describe the solution you'd like**

Ist es Möglich eine Json Table zu machen für Alle und für einzelne Provider?

LG
Sigi

**Comment by ticaki** [comment]
Meinst du sowas: 
<img width="906" alt="Bildschirmfoto 2023-10-01 um 00 12 44" src="https://github.com/ticaki/ioBroker.weather-warnings/assets/59184294/05436b2b-96af-4795-8a22-de0279ead4ef">

Das geht mit dem nächsten Upload so:

<img width="463" alt="Bildschirmfoto 2023-10-01 um 00 13 28" src="https://github.com/ticaki/ioBroker.weather-warnings/assets/59184294/306dd43b-4fe4-4fd0-94be-bd99bf2f150e">

**Comment by ticaki** [comment]
Done
