### ISSUE TITLE
Warntexte nach Vorlage in objects

### ISSUE THREAD

**Issue by yogiflop** [ticaki/ioBroker.weather-warnings#128]
Moin,
ich nutze noch andere Displays zur Anzeige der Meldungen, daher würde ich mir wünschen, das ich die fertigen Texte der Vorlagen unter Objekte abgreifen kann.

**Comment by ticaki** [comment]
Hallo,

sry für die lange Pause. Das sollte gehen, bin noch nicht wieder richtig drin, aber die Texte lassen sich ausgeben, wenn ich mich nicht falsch erinnere.

**Comment by ticaki** [comment]
Hab mich wieder erinnert wie das geht:

erstmal ein Bilder der Einstellungen:
<img width="953" alt="Bildschirmfoto 2024-11-11 um 17 05 11" src="https://github.com/user-attachments/assets/0088af53-44c1-44b3-b8f3-cbe461682b14">

Die Nachricht wird in eine benutzerdefinierten Key geschrieben

Dann sieht das in den States so aus:
<img width="1428" alt="Bildschirmfoto 2024-11-11 um 17 06 57" src="https://github.com/user-attachments/assets/11ab4ab8-be95-4776-862e-63c496ea33bd">

Damit dürfte das gelöst sein :)
