### ISSUE TITLE
Start- und Endzeit Darstellungsproblem

### ISSUE THREAD

**Issue by Norb1204** [ticaki/ioBroker.weather-warnings#140]
**Das Start- und Enddatum bei den verschiedenen Warnungen werden im Objektbaum nicht korrekt dargestellt (String anstelle von number):**
<img width="940" alt="image" src="https://github.com/user-attachments/assets/28470328-94fb-455c-8003-4c220dbb424c">

**Das führt bei der VIS-Anzeige zu Anzeigeproblemen:**
<img width="471" alt="image" src="https://github.com/user-attachments/assets/426adfbd-7acc-4c2d-b5db-62d743af458c">

**Comment by ticaki** [comment]
Hab das auf github behoben, muß noch testen ob die States sich selbst anpassen ohne gelöscht zu werden. die Pause war zu lange.
