### ISSUE TITLE
More template keys

### ISSUE THREAD

**Issue by ticaki** [ticaki/ioBroker.weather-warnings#18]
More template keys

- [x] Anzahl Warnungen
- [ ] Anzahl Warnungen vom Provider
- [ ] Index der aktuellen Warnung
- [ ] Index der aktuellen Warnung vom Provider

**Comment by rtwl21** [comment]
eventuell noch einen kurzen String für Mo, Di, Mi,... anstelle ausgeschrieben Montag, Dienstag, Mittwoch,...
Bezeichnung dafür könnte folgende sein: ${startdayofweekshort} und ${enddayofweekshort}

**Comment by rtwl21** [comment]
Dauer bis zum Beginn des Ereignis (Startzeit **minus** aktuelle Zeit) für Meldungen wie "Gewitter in 2 Std und 30 min" oder auch "Gewitter in 90 Minuten"

**Comment by ticaki** [comment]
Kurzform von Wochentage sind kein Problem
zeit bis muß ich drüber nachdenken wie ich das umsetzen könnte.

**Comment by ticaki** [comment]
Ideen aktualisiert

**Comment by ticaki** [comment]
Denke nicht das wir die brauchen
