### ISSUE TITLE
Improve telegram, pushover, whatsapp

### ISSUE THREAD

**Issue by ticaki** [ticaki/ioBroker.weather-warnings#22]
Add:
- [x] Telegram User/s
- [x] Telegram Chat id

- [x] Pushover Title (own template) 
- [x] Pushover Sounds
- [x] Pushover Line break

- [x] Whatsapp phonenumber

**Comment by rtwl21** [comment]
Bitte auch einen Zeilensprung für pushover möglich machen

**Comment by ticaki** [comment]
setze mal \n in das Template dafür und schaue ob es einen Zeilensprung gibt. Wenn nicht, teste ich es selbst und mache es möglich.

**Comment by rtwl21** [comment]
Hab schon \n \r und auch <br> getestet.
funktioniert nicht.
bei \n kommt dann der Buchstabe n in den Text.

**Comment by rtwl21** [comment]
Vielleicht hilft dir das:
bei Pushover Send sieht das Javascript (erstellt mit Blockly) so aus:
```
sendTo("pushover", "send", {
   message: (['Zeile 1','\n','Zeile 2'].join('')),
   sound: "",
   title: 'Betreff'
});
```

Mit ``title:`` sendet man also den Betreff/Titel der Pushover Meldung
mit ``\n`` kann man einen Zeilensprung machen.

direkt in den Vorlagen funktioniert das mit dem Zeilensprung aber, wie eh schon beschrieben, nicht.

Den Titel könnte man ja so einbinden:
![image](https://github.com/ticaki/ioBroker.weather-warnings/assets/100233609/b0ac7f20-2e1f-4ddc-8d85-2196a1deda8c)

**Comment by ticaki** [comment]
Title steht auf dem Plan, will da was besseres haben, als nur einen Standardtext. Mal sehen :)

**Comment by ticaki** [comment]
Ich "versuche" gerade eine "kaputte" Mitteilung durch das system zu bekommen, damit ich auch in RemoveAll zumindeste 1 Token habe, nächster Schritt ist das einen Title der auch diesen Token haben darf - Neue Warnung, Entwarnung und Gültige Warnung (letztes für manuellen Abruf)
