### ISSUE TITLE
Write and translate Readme

### ISSUE THREAD

**Issue by ticaki** [ticaki/ioBroker.weather-warnings#26]
Deutsch ist ebenfalls erwünscht. Bitte löscht den Vorlagen Text.
English is ok. Please remove the template text.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mcm1957** [comment]
Hinweis: 
Das README.md muss ausschließlich in English gehalten sein, ein deutsches oder zweisprachiges README.md ist nicht zulässig. Die Datei wird automatisch für die Webseite übersetzt und eine Mehrsprachigkeit stört diesen Prozess.

Ein README_de.md oder eine deutsche Doku im doc Verzeichnis ist ok, ebenso links auf andere Sprachen im main README.md
