### ISSUE TITLE
Icons für Warnungen

### ISSUE THREAD

**Issue by sigi2345** [ticaki/ioBroker.weather-warnings#28]
Bitte Icons für Warnungen hinzufügen.

**Comment by rtwl21** [comment]
könnte man diese Icons irgendwie selbst definieren?
ich persönlich hätte gerne für ZAMG die 4 Farben als icon (wie in den emojies zu finden (🟢🟡🟠🔴)
oder wäre das sowieso so geplant?

**Comment by ticaki** [comment]
Hm, hab doch tatsächlich einige Kommentare übersehen. Ich bin mir da nicht sicher wie ich das verwirklichen soll. Denke das einfachste ist, ich gebe Icons vor. Aber das passt dann i.d.R. nicht zur Oberfläche. Muß mal jemanden Fragen der ahnung davon hat.

**Comment by rtwl21** [comment]
Kein Stress damit. Dein Adapter steht ja noch am Anfang.
cool wäre halt icons für den Typ und auch Icons für den Level (diese hab ich oben gemeint)
Icons vorgeben ist sicher für den Anfang mal okay. individuell anpassbar wäre halt die Top Lösung 😊

**Comment by ticaki** [comment]
Problem solved!

beachte oberes und unteres Template
<img width="902" alt="Bildschirmfoto 2023-10-13 um 10 53 27" src="https://github.com/ticaki/ioBroker.weather-warnings/assets/59184294/e4afce15-3af6-4051-8424-b4f17f896aba">

Unicode geht nicht, mußt das Symbol rein kopieren.
<img width="424" alt="Bildschirmfoto 2023-10-13 um 10 53 43" src="https://github.com/ticaki/ioBroker.weather-warnings/assets/59184294/94c7d25d-ae10-4bf4-b450-0ad4d548f59d">

**Comment by ticaki** [comment]
@sigi2345
@rtwl21 
Wenn das eure Wünsche erfüllt kurzes ok bitte.

**Comment by rtwl21** [comment]
habs noch nicht getestet, aber ich denke damit kann ich was anfangen. Die emoji Icons reichen mir. Daher ist mein Wunsch soweit mal erfüllt.
