### ISSUE TITLE
hex-code selbst definieren können 

### ISSUE THREAD

**Issue by rtwl21** [ticaki/ioBroker.weather-warnings#30]
Wäre es möglich den hex Code der unterschiedlichen warnlevels selbst zu definieren? Ich hätte gerne die selben Farben wie ich auch in meiner vis verwende.
falls nicht auch kein Problem, dann wird ein binding helfen 😉

**Comment by ticaki** [comment]
Wenn ich mich recht entsinne hast du mir mal deine Hexcodes gegeben. ODer war das jemand anderes...

https://github.com/ticaki/ioBroker.weather-warnings/blob/c73e6a799d6fd5d078ddd953dc0643d7e608c934/src/lib/def/messages-def.ts#L156

Da sind die Hexcodes, wenn du andere willst, poste diese 7 Zeilen einfach hier wie du sie brauchst. @sigi2345  ist ok?

**Comment by sigi2345** [comment]
> @sigi2345 ist das ok?

Als Option  ja.

**Comment by ticaki** [comment]
Das kommt jetzt nicht sofort aber ich habe folgende Idee:

Vorlage

das ist die rot = ${[hex,hex,hex,hex]warncolornumber} 

geht nur mit Zahlen, 0 ist der erste eintrag links und dann wird das wiedergegeben was in dem [] steht.

**Comment by rtwl21** [comment]
ich will mich nicht mit meinen Farben aufdrängen. Dachte auch eher an das Objekt ``warnlevelcolorhex`` und weniger an einen Token. In den Benachrichtigungen möchte ich dann (wenn möglich) das Icon in der entsprechenden Farbe verwenden.

**Comment by ticaki** [comment]
Das ist in den Admin einzubauen ist Arbeit und es wird immer unübersichtlicher, so ein token kann man auch für anders gebrauchen.

**Comment by rtwl21** [comment]
alles gut. Kümmer dich um die wichtigen Sachen ;-)
ich hab ja keine Ahnung vom Adapter kreieren und wie aufwändig das alles ist.

**Comment by ticaki** [comment]
Ohne echte Warnungen kann ich nicht die wichtigen Sachen machen. Wie ist das was ich jetzt eingebaut habe. 

Für mich selbst habe ich dafür schon eine Anwendung, aber die hat nichts mit Wetter zu tun sondern kommt von meinen Skripten, wenn das sendTo() zum Adapter mal eingebaut sein sollte. Ich überschreibe dann den warntype mit offline, zu kalt usw. wenn meine Sensorüberwachung einen Fehler findet.

**Comment by rtwl21** [comment]
Für mich kann das Thema geschlossen werden, denn es ist mit eine CustomArray Vorlage einfach möglich, da diese ja auch als Objekte verfügbar sind:
![image](https://github.com/ticaki/ioBroker.weather-warnings/assets/100233609/ef034a06-7754-43fc-84e6-768d0155201f)

![image](https://github.com/ticaki/ioBroker.weather-warnings/assets/100233609/eb7a49d3-a311-4498-9722-b1c63ba08520)
