### ISSUE TITLE
Unterschiedliche Sounds bei Alexa ansagen

### ISSUE THREAD

**Issue by chris76e** [ticaki/ioBroker.weather-warnings#34]
Fände es gut wenn man zu jedem Arlarm einstellen kann welcher Sound kommt. Es gibt ja welche als Sturm, Regen, Donner...., gerne als "aktivere ExpertMode". 

Beispiel: wenn DWD vor Sturmwarnt ein Windgeräuch, wenn gewitter ein Donner usw.

**Comment by ticaki** [comment]
- [] add expert mode
- [] add detail sounds for alexa
