### ISSUE TITLE
States zusammenfassen

### ISSUE THREAD

**Issue by sigi2345** [ticaki/ioBroker.weather-warnings#36]
Bitte für folgende States ein Summary machen:

- [ ] weather-warnings.0.provider.zamg.xxxxxxxxx-xxxxxxxxxxx.formatedKeys.00.warntypename
 

https://forum.iobroker.net/topic/68595/test-adapter-weather-warnings/6?_=1697695366526

**Comment by ticaki** [comment]
- [ ] Level 
- [ ] Warntypeicons

**Comment by ticaki** [comment]
Ich glaub das hat sich mit der .alerts erweiterung dann erledigt/erfüllt.
