### ISSUE TITLE
Aussprache Alexa

### ISSUE THREAD

**Issue by chris76e** [ticaki/ioBroker.weather-warnings#45]
Finde die Aussprache bei Alexa von z.B. 

zweiundzwanzigster 

nicht so toll, wenn man es so 

zweiundzwan**zs**igster

schreibt hört es sich natürlicher an

**Comment by ticaki** [comment]
Hast recht, teste bitte mal alle durch, dann mache ich das so. Einbau wird wohl ähnlich lange dauern wie testen. :)

**Comment by chris76e** [comment]
Hast du von der Liste auch die deutsche Version damit ich das testen kann?

`<html><body>
<pre class="markdown-highlight"><code class="hljs json" data-lines="1">

{
--


</code></pre><pre class="markdown-highlight"><code class="hljs json" data-lines="1">                            <div class="hljs-ln-line">}</div></code></pre>
</body>
</html>`

**Comment by chris76e** [comment]
Sind nur die beiden die geändert werden müssen, alle anderen hören sich "Normal" an

`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chris/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chris/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



"22.":   "zweiundzwanzsigster",
--
"28.":   "achtundzwanzsigster",



</body>

</html>
`

**Comment by ticaki** [comment]
fixed with 0.4.2
