### ISSUE TITLE
neues Feld "Zeitraum"

### ISSUE THREAD

**Issue by rtwl21** [ticaki/ioBroker.weather-warnings#83]
Das neue Feld "Zeitraum" könnte so in etwa definiert werden:

wenn
startdayofweek = enddayofweek UND starttime = 00:00 UND endtime = 23:59
dann
value of startdayofweek
sonst
"undefined" oder einfach nur leer lassen.

**Comment by ticaki** [comment]
Ok ich baue das diese WE für ZAMG ein der Rest kann damit nix anfangen denke ich

**Comment by ticaki** [comment]
ist das Feld wie erwünscht?

**Comment by rtwl21** [comment]
auf dem ersten Blick sieht es gut aus.
hab aktuell eine Warnung von 00:00-23:59 und es steht "Samstag" im Objekt.
bleibt das Objekt leer, wenn der Zeitraum anders ist?

**Comment by ticaki** [comment]
Aktuell wird nur die Differenz betrachtet. Ist diese annähernd 24h wird der Starttag ausgegeben. Hm sollte vielleicht auch noch testen das die Start (Stunde) < 3 Das mache ich noch rein.

Ja bleibt leer wenn die Bedingungen nicht erfüllt sind.
